name: CI MLflow
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true  # Mandatory for your 375MB file

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.7"

      - name: Install dependencies
        run: |
          pip install mlflow pandas scikit-learn

      - name: Run MLflow Project
        run: mlflow run ./MLProject --no-conda
