name: CI MLflow

on:
  push:
    branches: [ "main" ]
  pull_request: 
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.10"

      - name: Install MLflow & Dependencies
        shell: bash -l {0}
        run: |
          conda install -c conda-forge conda-build -y
          pip install mlflow==3.11.1

      - name: Run MLflow Project
        shell: bash -l {0}
        run: |
          mlflow run . --experiment-name "Bitcoin Price Prediction" \
             -P epochs=2 \
             -P data_file="MLProject/preprocessed_bitcoin_data.csv"

      - name: Upload MLflow Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-results
          path: mlruns/
